name: covid_count
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^0.3.7
  http: ^0.13.0
  intl: ^0.17.0
  font_awesome_flutter: ^9.0.0
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/4.png"
  image_path_android: "assets/images/covcount.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/coronavirus.png
    - assets/images/syringe.png
    - assets/images/profile.jpeg
    - assets/images/medicine.png

  # fonts:
  #   - family: SourceSansPro
  #     fonts:
  #       - asset: assets/fonts/NunitoSans-Bold.ttf
  #       - asset: assets/fonts/NunitoSans-SemiBold.ttf
  #       - asset: assets/fonts/NunitoSans-Black.ttf
  #       - asset: assets/fonts/NunitoSans-Light.ttf
  #       - asset: assets/fonts/NunitoSans-Regular.ttf
  # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
